version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             gunicorn graacc.wsgi:application -b 0.0.0.0:8000 --workers 4"
    environment:
      DJANGO_SETTINGS_MODULE: graacc.settings
      SECRET_KEY: ${SECRET_KEY}


  nginx:
    image: "nginx:1.21.6-alpine"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf.template
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      BACKEND_URL: ${BACKEND_URL}
    command: /bin/sh -c "envsubst '\$$BACKEND_URL' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app

volumes:
  static-data:
  media-data: